###############################################################################
#                                                                             #
# neutron.mac                                                                 #
# 1 neutron fired in the room                                                 #
#                                                                             #
###############################################################################

# verbosities
/control/verbose 0
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1
#turn off the scintillation


/dmx/KillGammasInConcrete 0

# using GPS for ambe_spectrum:


/gps/pos/centre 1 0 0 m 

/gps/direction 0 0 1

/gps/particle neutron



# Log-spaced energy bins with equal probability
# 1e-5 eV = 1e-11 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-11 MeV
/run/beamOn 10000

# 1e-4 eV = 1e-10 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-10 MeV
/run/beamOn 10000

# 1e-3 eV = 1e-9 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-9 MeV
/run/beamOn 10000

# 1e-2 eV = 1e-8 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-8 MeV
/run/beamOn 10000

# 1e-1 eV = 1e-7 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-7 MeV
/run/beamOn 10000

# 1 eV = 1e-6 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-6 MeV
/run/beamOn 10000

# 10 eV = 1e-5 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-5 MeV
/run/beamOn 10000

# 100 eV = 1e-4 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-4 MeV
/run/beamOn 10000

# 1 keV = 1e-3 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-3 MeV
/run/beamOn 10000

# 10 keV = 1e-2 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-2 MeV
/run/beamOn 10000

# 100 keV = 1e-1 MeV
/gps/ene/type Mono
/gps/ene/mono 1e-1 MeV
/run/beamOn 10000

# 1 MeV
/gps/ene/type Mono
/gps/ene/mono 1 MeV
/run/beamOn 10000

# 10 MeV
/gps/ene/type Mono
/gps/ene/mono 10 MeV
/run/beamOn 10000




#/random/setDirectoryName ./seeds
#/random/setSavingFlag

/random/setSeeds 5338 17544

#/run/beamOn 10000000
#/run/beamOn 100000
#/run/beamOn 10

